//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ourShop.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesBook
    {
        public int Id { get; set; }
        public Nullable<int> IdCategoriesBook_Parent { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> ModifcatedBy { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
